package org.evoke.product.error;

public interface ErrorCode {

	int USER_ALREADY_EXISTS = 1000;
	int EMAIL_ALREADY_EXISTS = 1001;
	int USER_NOT_FOUND = 1002;
	int PASSWORD_NOT_VALID = 1003;
	int VALID_NUMBER_REQUIRED = 1004;
	int USER_DETAILS_OBJECT_NOT_FOUND = 1005;
	int EMAIL_NOT_VALID = 1006;
	int PRODUCT_NOT_VALID = 1007;
	int PRODUCT_NOT_FOUND = 1008;
	//int PRODUCT_NOT_VALID 
}
